version: "3"

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    networks:
      - keycloak_network

networks:
  keycloak_network:
    external: true
